# Generated by Django 4.1.7 on 2023-03-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoakuntansi', '0002_jurnal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurnal',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jurnal',
            name='file',
            field=models.FileField(null=True, upload_to='file/'),
        ),
    ]
