# Generated by Django 4.1.7 on 2023-03-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoakuntansi', '0003_alter_jurnal_date_alter_jurnal_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurnal',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
