# Generated by Django 4.1.7 on 2023-03-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoakuntansi', '0004_alter_jurnal_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='jurusan',
            new_name='kode_prodi',
        ),
        migrations.AlterField(
            model_name='user',
            name='kelas',
            field=models.CharField(max_length=100),
        ),
    ]
