# Generated by Django 4.1.7 on 2023-03-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoakuntansi', '0005_rename_jurusan_user_kode_prodi_alter_user_kelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kelas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='kode_prodi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nim',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
