# Generated by Django 4.1.7 on 2023-03-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoakuntansi', '0006_alter_user_kelas_alter_user_kode_prodi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipe',
            field=models.CharField(blank=True, choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('USER', 'User')], default='USER', max_length=255),
        ),
    ]
