# Generated by Django 4.1.7 on 2023-03-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoakuntansi', '0007_alter_user_tipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nama',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
