# Generated by Django 4.1.7 on 2023-03-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoakuntansi', '0008_alter_user_nama_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipe',
            field=models.CharField(blank=True, choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('USER', 'User'), ('PEMBIMBING', 'Pembimbing')], default='USER', max_length=255),
        ),
    ]
