# Generated by Django 4.1.7 on 2023-03-26 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repoakuntansi', '0009_user_nip_alter_user_tipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='TugasAkhir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(null=True)),
                ('catatan', models.TextField(null=True)),
                ('status', models.CharField(max_length=100)),
                ('file', models.FileField(null=True, upload_to='file/')),
                ('date', models.DateField(auto_now_add=True)),
                ('pembimbing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_pembimbing_manual_roats', to=settings.AUTH_USER_MODEL, verbose_name='Pembimbing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_user_manual_roats', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
