# Generated by Django 4.1.7 on 2023-03-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoakuntansi', '0010_tugasakhir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tugasakhir',
            name='judul',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tugasakhir',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
