# Generated by Django 4.1.7 on 2023-04-25 12:24

from django.db import migrations, models
import repoakuntansi.models


class Migration(migrations.Migration):

    dependencies = [
        ('repoakuntansi', '0011_alter_tugasakhir_judul_alter_tugasakhir_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tugasakhir',
            name='file',
            field=models.FileField(null=True, upload_to='file/', validators=[repoakuntansi.models.TugasAkhir.upload_pdf_validator]),
        ),
    ]
