# Generated by Django 4.1.7 on 2023-04-25 13:11

from django.db import migrations, models
import repoakuntansi.models


class Migration(migrations.Migration):

    dependencies = [
        ('repoakuntansi', '0012_alter_tugasakhir_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurnal',
            name='file',
            field=models.FileField(null=True, upload_to='file/', validators=[repoakuntansi.models.Jurnal.upload_pdf_validator]),
        ),
    ]
