# Generated by Django 4.1.7 on 2023-05-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoakuntansi', '0013_alter_jurnal_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugasakhir',
            name='komentar',
            field=models.TextField(null=True),
        ),
    ]
